version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    default_labels:
      - "deps_bot" # this is to help our PR list to filter
  - package_manager: "java:maven"
    directory: "/"
    update_schedule: "daily"
    default_labels:
      - "deps_bot" # this is to help our PR list to filter