version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"
    default_labels:
      - "axe_api_deps_bot"
  - package_manager: "java:maven"
    directory: "/"
    update_schedule: "weekly"
    default_labels:
      - "axe_api_deps_bot"